connect / as sysdba
create spfile from pfile;
startup nomount
CREATE DATABASE obbdev
EXTENT MANAGEMENT LOCAL
DEFAULT TEMPORARY TABLESPACE temp
UNDO TABLESPACE undotbs1
DEFAULT TABLESPACE users
CHARACTER SET AL32UTF8
NATIONAL CHARACTER SET UTF8;
CREATE TABLESPACE obbdev LOGGING 
     DATAFILE '/u01/app/oracle/oradata/obbdev/OBBDEV01.dbf' 
     SIZE 30G AUTOEXTEND ON MAXSIZE UNLIMITED ONLINE
     EXTENT MANAGEMENT LOCAL;
exit
